### ISSUE TITLE
ModuleNotFoundError: No module named 'habitat_baselines.il.data'

### ISSUE THREAD

**Issue by zhangpingrui** [Jbwasse2/XGX#1]
Hi! Thanks for your great work!

Although I follow your instructions to install all dependencies, when I run this command 

`python run.py --exp-config ./configs/experiments/XGX.yaml --run-type eval`

I found the error that 

`ModuleNotFoundError: No module named 'habitat_baselines.il.data'`

And then I find that the filefolder `habitat-lab/habitat-baselines/il` in this repo does not have `data` folder.

![image](https://github.com/Jbwasse2/XGX/assets/74910671/eebc9217-6e07-4522-8374-ea128bcecf01)

So I think maybe the version of habitat-lab package in this repo was wrong, but which version should I clone from habitat-lab in this project?

Or there were other reasons leading to this problem. How can I solve it?

**Comment by Jbwasse2** [comment]
Sorry for the delay! I don't have enough information to reproduce this error locally, but I think I might have an idea of what the issue is. Can you supply the full error message (what line number/function raised this error)?

**Comment by zhangpingrui** [comment]
> Sorry for the delay! I don't have enough information to reproduce this error locally, but I think I might have an idea of what the issue is. Can you supply the full error message (what line number/function raised this error)?

Sorry I already couldn't find that full error message. I use a part of this code not all to avoid errors. Thanks for your reply!
