### ISSUE TITLE
The results in MatterPort3d Data.

### ISSUE THREAD

**Issue by BigTree765** [Jbwasse2/XGX#2]
Thank you for your excellent work. It has achieved great results in the HM3D dataset. However, I would like to inquire about the results in the MP3D dataset, as there are some works that only evaluate performance on this dataset.

**Comment by Jbwasse2** [comment]
Thank you for your kind words :). I only trained/tested a model in HM3D. Unfortunately, I do not have a model trained for MP3D and do not currently have the resources at the moment to train this.
